---
build_from:
  aarch64: hassioaddons/base-aarch64:11.0.0
  amd64: hassioaddons/base-amd64:11.0.0
  armhf: hassioaddons/base-armhf:11.0.0
  armv7: hassioaddons/base-armv7:11.0.0
  i386: hassioaddons/base-i386:11.0.0