---
name: RTLAMR-RTLCOLLECT
version: 1.0.0
slug: rtlamr_collect
description: RTLAMR and RTL-COLLECT
url: https://github.com/debsahu/hassio-rtlamr-addon
startup: application
ingress: false
panel_icon: mdi:radio-tower
panel_title: RTLAMR & RTL-COLLECT
arch:
  - aarch64
  - amd64
  - armv7
  - armhf
  - i386
map: ["config:rw"]
options:
  RTLAMR_FORMAT: json
  RTLAMR_MSGTYPE: r900
  RTLAMR_CENTERFREQ: 917000000
  RTLAMR_FILTERID: []
  COLLECT_INFLUXDB_HOSTNAME: http://a0d7b954-influxdb:8086/
  COLLECT_INFLUXDB_DATABASE: rtlamr
  COLLECT_INFLUXDB_TOKEN: rtlamr:rtlamr
  COLLECT_INFLUXDB_ORG: doesnotmeananything
  COLLECT_INFLUXDB_BUCKET: rtlamr
  COLLECT_INFLUXDB_MEASUREMENT: rtlamr
  COLLECT_STRICTIDM: 1
  RTL_TCP_SERVER: 127.0.0.1:1234
schema:
  log_level: list(trace|debug|info|notice|warning|error|fatal)?
  RTLAMR_FORMAT: str
  RTLAMR_MSGTYPE: str
  RTLAMR_CENTERFREQ: int
  RTLAMR_FILTERID: []
  COLLECT_INFLUXDB_HOSTNAME: url
  COLLECT_INFLUXDB_DATABASE: str
  COLLECT_INFLUXDB_TOKEN: str
  COLLECT_INFLUXDB_ORG: str
  COLLECT_INFLUXDB_BUCKET: str
  COLLECT_INFLUXDB_MEASUREMENT: str
  COLLECT_STRICTIDM: int
  RTL_TCP_SERVER: match(^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5]):[0-9]+$)