---
name: RTLAMR-RTLCOLLECT
version: 1.0.0
slug: rtlamr_collect
description: RTLAMR and RTL-COLLECT
url: https://github.com/debsahu/hassio-rtlamr-addon
startup: services
ingress: false
panel_icon: mdi:radio-tower
panel_title: RTLAMR & RTL-COLLECT
arch:
  - aarch64
  - amd64
  - armv7
  - armhf
  - i386
map: ["config:rw"]
usb: true
options:
  RTLAMR_MSGTYPE: r900
  RTLAMR_CENTERFREQ: 917000000
  COLLECT_INFLUXDB_HOSTNAME: http://a0d7b954-influxdb:8086/
  COLLECT_INFLUXDB_DATABASE: rtlamr
  COLLECT_INFLUXDB_TOKEN: rtlamr:rtlamr
  COLLECT_INFLUXDB_ORG: doesnotmeananything
  COLLECT_INFLUXDB_BUCKET: rtlamr
  COLLECT_INFLUXDB_MEASUREMENT: rtlamr
  COLLECT_STRICTIDM: 1
schema:
  log_level: list(trace|debug|info|notice|warning|error|fatal)?
  RTLAMR_MSGTYPE: list(all|scm|scm+|idm|netidm|r900|r900bcd)
  RTLAMR_CENTERFREQ: match(^([0-9]{9})$)
  RTLAMR_FILTERID: int?
  COLLECT_INFLUXDB_HOSTNAME: url
  COLLECT_INFLUXDB_DATABASE: str
  COLLECT_INFLUXDB_TOKEN: str
  COLLECT_INFLUXDB_ORG: str
  COLLECT_INFLUXDB_BUCKET: str
  COLLECT_INFLUXDB_MEASUREMENT: str
  COLLECT_STRICTIDM: int